name: Copilot Error Check

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  check-errors:
    runs-on: self-hosted
    steps:
      # - name: Install Copilot CLI
      #   uses: actions/setup-copilot@v0
      #   with:
      #     github-token: ${{ secrets.COPILOT_TOKEN }}

      - name: Run Copilot query and print output
        # env:
        #   COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          set -e
          OUTPUT=$(copilot -p "Always use the aggirigated span. Can you comapre the error, cpu, memory utilization between current version with the previous version of  mrportal-cps-mw in uat env. after that please share your verdit that we should proceed with this latest tag rollout to production, also share a comparison between two tags")
          echo "$OUTPUT"
          echo "$OUTPUT" >> "$GITHUB_STEP_SUMMARY"
